ARTIFACTS_DIR: "../artifacts"
MODEL:
  img_size: [224, 224, 3]
  img_encoder:
    pretrained: True
DATA:
  dataset: "Flickr8kDataset"
  batch_size: 2
  root_dir: "../data"
OPTIM:
  loss: ""
  optimizer: "AdamW"
  lr: 0.0001
  num_epochs: 100
  eval_every: 5
  gradient_clip: true
  scheduler: ""
  T_max: 100
  eta_min: 0.000001
